Fixes 2/3 of #86
dscnitrourkela/project-avocado pull request #134
Opened 2020-11-08 19:40 UTC by abhibhaw

- [ ] Subscribed to Academic & Other Notification Channel

- [ ] Saved Unique Device Tokens to Firestore

2020-11-11 20:08 UTC, abhibhaw commented
## Added Flex to fix this.

# Before
___________________________________________________________

![Screenshot_1605124478](https://user-images.githubusercontent.com/39991296/98858921-66dee280-2487-11eb-8f79-15001318c590.png)

# After 
___________________________________________________________

![Screenshot_1605124490](https://user-images.githubusercontent.com/39991296/98859046-94c42700-2487-11eb-809a-bff71b84fc42.png)

2020-11-11 20:10 UTC, abhibhaw commented
# Settings Page UI

![Screenshot_1605124472](https://user-images.githubusercontent.com/39991296/98859258-e66cb180-2487-11eb-9d9c-5d8cf61268b7.png)
![Screenshot_1605124466](https://user-images.githubusercontent.com/39991296/98859265-e8367500-2487-11eb-878c-84363c2e2b0c.png)

2020-11-12 04:00 UTC, DesignrKnight requested changes

2020-11-12 04:00 UTC, DesignrKnight commented
@Thesmader 
Over to you

2020-11-13 16:21 UTC, DesignrKnight commented
@abhibhaw 
Do mention when you do the changes discussed. Will approve and merge

2020-11-13 16:32 UTC, abhibhaw commented
@DesignrKnight Changes are throwing a few errors 😢 I am on it!!

2020-11-13 18:31 UTC, abhibhaw commented on scp/lib/HomePage.dart
>      _fcm.subscribeToTopic('ics-not');
Done!

2020-11-13 18:31 UTC, abhibhaw commented on scp/lib/HomePage.dart
> +        .where('devToken', isEqualTo: token)
Done

2020-11-13 18:31 UTC, abhibhaw commented on scp/lib/drawer_screens/settings.dart
> +                          }
Done

2020-11-13 18:32 UTC, abhibhaw commented
@DesignrKnight @Thesmader All set to go 👍

2020-11-13 19:02 UTC, Thesmader requested changes
Several small issues.

2020-11-13 19:07 UTC, Thesmader approved these changes

2020-11-13 19:10 UTC, Thesmader commented
Good to go!

2020-11-14 05:11 UTC, DesignrKnight approved these changes

2020-11-14 05:13 UTC, DesignrKnight commented
@abhibhaw @nayakastha @SriramPatibanda 
I am merging this. Once that is done. This state of the project, planning to push to Play Store and inform SAC. Do check thoroughly. 

Also, now that we have two notification channel. We need Firebase Cloud Functions for the same. I will explain the existing one so that one of you can modify that

2020-11-14 05:14 UTC, merged