Refactored Appointments page
dscnitrourkela/project-avocado pull request #197
Opened 2021-01-05 12:57 UTC by Priya-81199

Created appointments_view and appointments_viewmodel inside the Appointments folder

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-01-12 11:28 UTC, Thesmader commented on scp/lib/services/firebase_analytics_service.dart
> +}
```suggestion
}

```

2021-01-12 13:53 UTC, SriramPatibanda requested changes
Have suggested very minor changes, please do those and commit, apart from that the code looks good. Great job 👍🏻

2021-01-12 13:53 UTC, SriramPatibanda commented on scp/lib/Appointments/appointments_viewmodel.dart
> +}
Add a blank line at the end of every file.
```suggestion
}

```

2021-01-12 13:53 UTC, SriramPatibanda commented on scp/lib/Appointments/appointments_viewmodel.dart
> +  getDate() async {
```suggestion
 void getDate() async {
```

2021-01-12 13:53 UTC, SriramPatibanda commented on scp/lib/Appointments/appointments_viewmodel.dart
> +    print(counselDay + 'hola');
try not to print anything to the console.
```suggestion

```

2021-01-12 15:27 UTC, SriramPatibanda approved these changes

2021-01-13 05:09 UTC, DesignrKnight commented
![image](https://user-images.githubusercontent.com/27865704/104409124-92677180-558b-11eb-9aaf-fca0f0e46254.png)
Can you resolve these?

2021-01-13 17:23 UTC, Thesmader approved these changes
LGTM

2021-01-13 17:24 UTC, merged